#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignyourselfHelpers
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Account\Facebook.cshtml"
    using System.Collections.Specialized;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Account\Facebook.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 2 "..\..\Views\Account\Facebook.cshtml"
    using System.Security;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Account\Facebook.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 4 "..\..\Views\Account\Facebook.cshtml"
    using System.Web.WebPages.Scope;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Views\Account\Facebook.cshtml"
    using Microsoft.Web.Helpers;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Account\Facebook.cshtml"
    using WebMatrix.Data;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Account\Facebook.cshtml"
    using WebMatrix.WebData;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.3.2.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Facebook.cshtml")]
    public class Facebook : System.Web.Mvc.WebViewPage<dynamic>
    {
        
        #line 11 "..\..\Views\Account\Facebook.cshtml"

    
    private const string FacebookCredentialsTableName = "webpages_FacebookCredentials";
    private const string FacebookCredentialsIdColumn = "FacebookId";
    private const string FacebookCredentialsUserIdColumn = "UserId";

    private const string DefaultUserIdColumn = "UserId";
    private const string DefaultUserNameColumn = "UserName";
    private const string DefaultUserTableName = "User";

    private const string DefaultFacebookPerms = "email";
    private const string DefaultCallbackUrl = "~/Account/Facebook/Login";
    private const string FacebookApiProfileUrl = "https://graph.facebook.com/me";

    private static readonly object _isInitializedKey = new object();
    private static readonly object _membershipDBNameKey = new object();
    private static readonly object _appIdKey = new object();
    private static readonly object _appSecretKey = new object();
    private static readonly object _language = new object();

    public static bool HasMembershipIntegration
    {
        get
        {
            return !MembershipDBName.IsEmpty();
        }
    }

    public static bool IsFacebookUserAuthenticated
    {
        get
        {
            return !GetFacebookCookieInfo("uid").IsEmpty();
        }
    }

    public static bool IsFacebookUserAssociated
    {
        get
        {
            return !GetAssociatedMembershipUserName().IsEmpty();
        }
    }

    public static bool IsInitialized
    {
        get
        {
            return (bool)(ScopeStorage.CurrentScope[_isInitializedKey] ?? false);
        }

        private set
        {
            ScopeStorage.CurrentScope[_isInitializedKey] = value;
        }
    }

    public static string MembershipDBName
    {
        get
        {
            return (string)(ScopeStorage.CurrentScope[_membershipDBNameKey] ?? "");
        }

        set
        {
            ScopeStorage.CurrentScope[_membershipDBNameKey] = value;
        }
    }

    public static string AppId
    {
        get
        {
            return (string)(ScopeStorage.CurrentScope[_appIdKey] ?? "");
        }

        set
        {
            ScopeStorage.CurrentScope[_appIdKey] = value;
        }
    }

    public static string AppSecret
    {
        get
        {
            return (string)(ScopeStorage.CurrentScope[_appSecretKey] ?? "");
        }

        set
        {
            ScopeStorage.CurrentScope[_appSecretKey] = value;
        }
    }

    public static string Language
    {
        get
        {
            return (string)(ScopeStorage.CurrentScope[_language] ?? "en_US");
        }

        set
        {
            ScopeStorage.CurrentScope[_language] = value;
        }
    }

    ///<summary>
    /// Initialize the helper with your Facebook application settings. 
    /// 
    /// If the 'membershipDBName' parameter is specified, Facebook membership integration will be enabled, 
    /// allowing users to register and associate their Facebook user account (identified with the e-mail) 
    /// with your site membership and the WebSecurity helper. 
    /// In this case, the helper will initialize the WebSecurity WebMatrix helper automatically (if not done previously) 
    /// and the store the Facebook membership information in the 'membershipDbName' database.    
    ///</summary>
    ///<param name="appId">Facebook application id.</param>        
    ///<param name="appSecret">Facebook application secret.</param>   
    ///<param name="membershipDBName">Name of the database used for storing the membership data.</param>   
    public static void Initialize(string appId, string appSecret, string membershipDbName = "")
    {
        AppId = appId;
        AppSecret = appSecret;
        IsInitialized = true;

        if (!membershipDbName.IsEmpty())
        {
            MembershipDBName = membershipDbName;

            InitializeMembershipProviderIfNeeded();
            InitializeFacebookTableIfNeeded();
        }
    }

    ///<summary>
    /// Retrieves the Facebook profile of current logged in user.
    ///</summary>
    public static UserProfile GetFacebookUserProfile()
    {
        var accessToken = GetFacebookCookieInfo("access_token");

        if (accessToken.IsEmpty())
        {
            return null;
        }

        var userProfileUrl = new Uri(string.Format("{0}?access_token={1}", FacebookApiProfileUrl, accessToken));

        var receiveStream = new WebClient().OpenRead(userProfileUrl);
        var result = new StreamReader(receiveStream).ReadToEnd();
        var profile = Json.Decode<UserProfile>(result);

        return profile;
    }

    ///<summary>
    /// Associates the specified User Name (e.g. email, depending on your membership model) with the current Facebook User Id from the logged user.
    ///</summary>
    ///<param name="userId">The user name to associate the current logged-in facebook account to.</param>
    public static void AssociateMembershipAccount(string userName)
    {
        if (!IsFacebookUserAuthenticated)
        {
            throw new InvalidOperationException("No Facebook user is authenticated.");
        }

        if (IsFacebookUserAssociated)
        {
            throw new InvalidOperationException("The authenticated Facebook user is already associated to a membership account.");
        }

        using (Database db = Database.Open(MembershipDBName))     
        {
            var facebookUserId = GetFacebookCookieInfo("uid").As<long>();

            var userId =  WebSecurity.GetUserId(userName);
            db.Execute(string.Format("INSERT INTO {0} ({1}, {2}) VALUES (@0, @1)", FacebookCredentialsTableName, FacebookCredentialsUserIdColumn, FacebookCredentialsIdColumn), userId, facebookUserId);

            // User is registered in the application
            FormsAuthentication.SetAuthCookie(userName, false);
        }
    }

    public static bool MembershipLogin()
    {
        var user = GetAssociatedMembershipUserName();

        if (!user.IsEmpty())
        {
            // User is registered in the application
            FormsAuthentication.SetAuthCookie(user, false);
            return true;
        }
        else
        {
            return false;
        }
    }

    private static void InitializeMembershipProviderIfNeeded()
    {
        var provider = GetMembershipProvider();

        if (IsMembershipProviderInitialized(provider))
        {
            WebSecurity.InitializeDatabaseConnection(MembershipDBName, DefaultUserTableName, DefaultUserIdColumn, DefaultUserNameColumn, true);
        }
    }

    private static void InitializeFacebookTableIfNeeded()
    {
        var provider = GetMembershipProvider();
        var db = Database.Open(MembershipDBName);
        var table = db.QuerySingle("SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @0", FacebookCredentialsTableName);

        if (table == null)
        {
            db.Execute(string.Format("CREATE TABLE {0} ({1} INT NOT NULL, {2} BIGINT NOT NULL)", FacebookCredentialsTableName, FacebookCredentialsUserIdColumn, FacebookCredentialsIdColumn));
        }
    }

    private static string GetAssociatedMembershipUserName()
    {
        var userName = "";

        if (IsFacebookUserAuthenticated)
        {
            var db = Database.Open(MembershipDBName);
            var provider = GetMembershipProvider();

            var userId = db.QueryValue(string.Format("SELECT {0} FROM {1} WHERE {2} = LOWER(@0)", FacebookCredentialsUserIdColumn, FacebookCredentialsTableName, FacebookCredentialsIdColumn), GetFacebookCookieInfo("uid"));
            if (userId != null)
            {
                userName = GetUserName(userId);
            }
        }

        return userName;
    }

    private static string GetUserName(int userId)
    {
        var userName = "";

        var db = Database.Open(MembershipDBName);
        var provider = GetMembershipProvider();
        userName = db.QueryValue(string.Format("SELECT {0} FROM {1} WHERE {2} = @0", provider.UserNameColumn, provider.UserTableName, provider.UserIdColumn), userId);

        return userName;
    }

    private static SimpleMembershipProvider GetMembershipProvider()
    {
        var provider = new SimpleMembershipProvider(Membership.Provider);
        if (provider == null)
        {
            throw new InvalidOperationException("Simple Membership Provider not found.");
        }

        return provider;
    }

    private static bool IsMembershipProviderInitialized(SimpleMembershipProvider provider)
    {
        return provider.UserTableName.IsEmpty() || provider.UserIdColumn.IsEmpty() || provider.UserNameColumn.IsEmpty();
    }

    private static string GetFacebookCookieInfo(string key)
    {
        var request = HttpContext.Current.Request;
        var name = string.Format("fbs_{0}", AppId);

        if (request.Cookies[name] != null)
        {
            var value = request.Cookies[name].Value;
            var args = HttpUtility.ParseQueryString(value.Replace("\"", ""));

            if (!IsFacebookCookieValid(args))
            {
                throw new SecurityException("Invalid Facebook cookie.");
            }

            return args[key];
        }
        else
        {
            return "";
        }
    }

    private static bool IsFacebookCookieValid(NameValueCollection args)
    {
        var payload = new StringBuilder();
        foreach (var key in args.AllKeys)
        {
            if (key != "sig")
            {
                payload.AppendFormat("{0}={1}", key, args[key]);
            }
        }

        payload.Append(AppSecret);

        var md5 = System.Security.Cryptography.MD5CryptoServiceProvider.Create();
        var hash = md5.ComputeHash(Encoding.ASCII.GetBytes(payload.ToString()));
        var signature = new StringBuilder();
        for (int i = 0; i < hash.Length; i++)
        {
            signature.Append(hash[i].ToString("X2"));
        }

        return string.Equals(args["sig"], signature.ToString(), StringComparison.InvariantCultureIgnoreCase);
    }

    public class UserProfile
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Link { get; set; }
        public string Bio { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Timezone { get; set; }
        public string Locale { get; set; }
        public string Updated_Time { get; set; }
    }

        #line default
        #line hidden

public System.Web.WebPages.HelperResult GetInitializationScripts()
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 348 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <div id=\"fb-root\"></div>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <script type=\"text/javascript\">\r\n        window.fbAsyncInit = function() {\r\n " +
"           FB.init({appId: \'");



#line 352 "..\..\Views\Account\Facebook.cshtml"
WriteTo(@__razor_helper_writer, AppId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\', status: true, cookie: true, xfbml: true});\r\n        };\r\n        (function() {\r" +
"\n            var e = document.createElement(\'script\'); e.async = true;\r\n        " +
"    e.src = document.location.protocol +\r\n            \'//connect.facebook.net/");



#line 357 "..\..\Views\Account\Facebook.cshtml"
      WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "/all.js\';\r\n            document.getElementById(\'fb-root\').appendChild(e);\r\n      " +
"  }());\r\n    \r\n        function loginRedirect(url) { window.location = url; }\r\n " +
"   </script>\r\n");



#line 363 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult LoginButton(
    string registerUrl,
    string returnUrl = "~/",
    string callbackUrl = DefaultCallbackUrl,
    string buttonText = "",
    bool autoLogoutLink = false,
    string size = "medium",
    string length = "long",
    bool showFaces = false,
    string extendedPermissions = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 399 "..\..\Views\Account\Facebook.cshtml"
     

        var redirectUrl = Href(string.Format("{0}?registerUrl={1}&returnUrl={2}", callbackUrl, HttpUtility.UrlEncode(registerUrl), HttpUtility.UrlEncode(returnUrl)));
        var onLogin = string.Format("loginRedirect('{0}')", redirectUrl);
        extendedPermissions = extendedPermissions.IsEmpty() ? "email" : string.Concat("email,", extendedPermissions);


#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <fb:login-button autologoutlink=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
      WriteTo(@__razor_helper_writer, autoLogoutLink);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" size=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                             WriteTo(@__razor_helper_writer, size);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" length=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                                            WriteTo(@__razor_helper_writer, length);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" onlogin=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                                                              WriteTo(@__razor_helper_writer, onLogin);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" show-faces=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                                                                                    WriteTo(@__razor_helper_writer, showFaces);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" perms=\"");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                                                                                                       WriteTo(@__razor_helper_writer, extendedPermissions);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 405 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                             WriteTo(@__razor_helper_writer, buttonText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</fb:login-button>        \r\n");



#line 406 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult LoginButtonTagOnly(
    string buttonText = "",
    bool autoLogoutLink = false,
    string size = "long",
    string length = "short",
    string onLogin = "",
    bool showFaces = false,
    string extendedPermissions = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 435 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <fb:login-button autologoutlink=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
      WriteTo(@__razor_helper_writer, autoLogoutLink);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" size=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                             WriteTo(@__razor_helper_writer, size);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" length=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                                            WriteTo(@__razor_helper_writer, length);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" onlogin=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                                                              WriteTo(@__razor_helper_writer, onLogin);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" show-faces=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                                                                                    WriteTo(@__razor_helper_writer, showFaces);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" perms=\"");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                                                                                                       WriteTo(@__razor_helper_writer, extendedPermissions);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\">");



#line 436 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                             WriteTo(@__razor_helper_writer, buttonText);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "</fb:login-button>\r\n");



#line 437 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult LikeButton(
            string href = "",
            string buttonLayout = "standard",
            bool showFaces = true,
            int width = 450,
            int height = 80,
            string action = "like",
            string font = "",
            string colorScheme = "light",
            string refLabel = ""
            )
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 478 "..\..\Views\Account\Facebook.cshtml"
         
                if (href.IsEmpty())
                {
                    href = Request.Url.ToString();
                }
        

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <iframe src=\"http://www.facebook.com/plugins/like.php?href=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                WriteTo(@__razor_helper_writer, href);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&layout=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                             WriteTo(@__razor_helper_writer, buttonLayout);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&show_faces=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                      WriteTo(@__razor_helper_writer, showFaces);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&width=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                       WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&action=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                     WriteTo(@__razor_helper_writer, action);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&colorscheme=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                         WriteTo(@__razor_helper_writer, colorScheme);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&height=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                             WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&font=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                          WriteTo(@__razor_helper_writer, font);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&locale=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                       WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&ref=");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                     WriteTo(@__razor_helper_writer, refLabel);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                           WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px; height:");



#line 484 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                                              WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px;\" allowTransparency=\"true\"></iframe>\r\n");



#line 485 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult Comments(
            string xid = "",
            int width = 550,
            int numPosts = 10,
            bool reverseOrder = false,
            bool removeRoundedBox = false)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 511 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden



#line 512 "..\..\Views\Account\Facebook.cshtml"
WriteLiteralTo(@__razor_helper_writer, "    <fb:comments ");

#line default
#line hidden


#line 512 "..\..\Views\Account\Facebook.cshtml"
                  if (!xid.IsEmpty())
                 {
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");

WriteLiteralTo(@__razor_helper_writer, "xid=\"");



#line 513 "..\..\Views\Account\Facebook.cshtml"
WriteTo(@__razor_helper_writer, xid);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"");

WriteLiteralTo(@__razor_helper_writer, " ");



#line 513 "..\..\Views\Account\Facebook.cshtml"
                                           }
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "numposts=\"");



#line 513 "..\..\Views\Account\Facebook.cshtml"
                       WriteTo(@__razor_helper_writer, numPosts);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" width=\"");



#line 513 "..\..\Views\Account\Facebook.cshtml"
                                         WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" reverse=\"");



#line 513 "..\..\Views\Account\Facebook.cshtml"
                                                          WriteTo(@__razor_helper_writer, reverseOrder);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" simple=\"");



#line 513 "..\..\Views\Account\Facebook.cshtml"
                                                                                 WriteTo(@__razor_helper_writer, removeRoundedBox);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" ></fb:comments>\r\n");



#line 514 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult Recommendations(
            string site = "",
            int width = 300,
            int height = 300,
            bool showHeader = true,
            string colorScheme = "light",
            string font = "",
            string borderColor = "",
            string filter = "",
            string refLabel = ""
    )
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 555 "..\..\Views\Account\Facebook.cshtml"
     	
        if (site.IsEmpty())
        {
            site = Request.Url.Host;
        }
        

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <iframe src=\"http://www.facebook.com/plugins/recommendations.php?site=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                           WriteTo(@__razor_helper_writer, site);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&width=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                       WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&height=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                     WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&header=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                    WriteTo(@__razor_helper_writer, showHeader);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&colorscheme=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                            WriteTo(@__razor_helper_writer, colorScheme);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&font=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                              WriteTo(@__razor_helper_writer, font);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&border_color=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                 WriteTo(@__razor_helper_writer, borderColor);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&filter=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                     WriteTo(@__razor_helper_writer, filter);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&ref=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                 WriteTo(@__razor_helper_writer, refLabel);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&locale=");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                  WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                                        WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px; height:");



#line 561 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                                                           WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px;\" allowTransparency=\"true\"></iframe>\r\n");



#line 562 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult LikeBox(
            string href,
            int width = 292,
            int height = 587,
            string colorScheme = "light",
            int connections = 10,
            bool showStream = true,
            bool showHeader = true)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 595 "..\..\Views\Account\Facebook.cshtml"
                     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <iframe src=\"http://www.facebook.com/plugins/likebox.php?href=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                   WriteTo(@__razor_helper_writer, href);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&width=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                               WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&height=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                             WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&colorscheme=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                 WriteTo(@__razor_helper_writer, colorScheme);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&connections=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                          WriteTo(@__razor_helper_writer, connections);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&stream=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                              WriteTo(@__razor_helper_writer, showStream);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&header=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                 WriteTo(@__razor_helper_writer, showHeader);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&locale=");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                    WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                          WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px; height:");



#line 596 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                             WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px;\" allowTransparency=\"true\"></iframe>                \r\n");



#line 597 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult Facepile(
            int maxRows = 1,
            int width = 200)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 613 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t<fb:facepile max-rows=\"");



#line 614 "..\..\Views\Account\Facebook.cshtml"
WriteTo(@__razor_helper_writer, maxRows);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" width=\"");



#line 614 "..\..\Views\Account\Facebook.cshtml"
          WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"></fb:facepile>\r\n");



#line 615 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult LiveStream(
            int width = 400,
            int height = 500,
            string xid = "",
            string viaUrl = "",
            bool allwaysPostToFriends = false)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 641 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <iframe src=\"http://www.facebook.com/plugins/live_stream_box.php?app_id=");



#line 642 "..\..\Views\Account\Facebook.cshtml"
                                             WriteTo(@__razor_helper_writer, AppId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&width=");



#line 642 "..\..\Views\Account\Facebook.cshtml"
                                                          WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&height=");



#line 642 "..\..\Views\Account\Facebook.cshtml"
                                                                        WriteTo(@__razor_helper_writer, height);

#line default
#line hidden



#line 642 "..\..\Views\Account\Facebook.cshtml"
                                                                                                               if (!xid.IsEmpty())
                                                                                                              {
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");

WriteLiteralTo(@__razor_helper_writer, "&xid=");



#line 643 "..\..\Views\Account\Facebook.cshtml"
                                                                                            WriteTo(@__razor_helper_writer, xid);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");



#line 643 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                       }
#line default
#line hidden



#line 643 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                         if (!xid.IsEmpty())
                                                                                                                                                             {
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");

WriteLiteralTo(@__razor_helper_writer, "&via_url=");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                               WriteTo(@__razor_helper_writer, viaUrl);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, " ");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                             }
#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&always_post_to_friends=");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                       WriteTo(@__razor_helper_writer, allwaysPostToFriends);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&locale=");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                    WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                                                          WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px; height:");



#line 644 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                                                                                                                                             WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "px;\" allowTransparency=\"true\"></iframe>\r\n");



#line 645 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult ActivityFeed(
            string site = "",
            int width = 300,
            int height = 300,
            bool showHeader = true,
            string colorScheme = "light",
            string font = "",
            string borderColor = "",
            bool showRecommendations = false)
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 682 "..\..\Views\Account\Facebook.cshtml"
     
                if (site.IsEmpty())
                {
                    site = Request.Url.Host;
                }
                

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <iframe src=\"http://www.facebook.com/plugins/activity.php?site=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                    WriteTo(@__razor_helper_writer, site);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&width=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                WriteTo(@__razor_helper_writer, width);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&height=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                              WriteTo(@__razor_helper_writer, height);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&header=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                             WriteTo(@__razor_helper_writer, showHeader);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&colorscheme=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                                                     WriteTo(@__razor_helper_writer, colorScheme);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&font=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                       WriteTo(@__razor_helper_writer, font);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&border_color=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                          WriteTo(@__razor_helper_writer, borderColor);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&recommendations=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                       WriteTo(@__razor_helper_writer, showRecommendations);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "&locale=");



#line 688 "..\..\Views\Account\Facebook.cshtml"
                                                                                                                                                                                                   WriteTo(@__razor_helper_writer, Language);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\" scrolling=\"no\" frameborder=\"0\" style=\"border:none; overflow:hidden; width:300px" +
"; height:300px;\" allowTransparency=\"true\"></iframe>\r\n");



#line 689 "..\..\Views\Account\Facebook.cshtml"

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult OpenGraphRequiredProperties(
    string siteName,
    string title,
    string type,
    string url,
    string imageUrl,
    string description = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 720 "..\..\Views\Account\Facebook.cshtml"
       

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:site_name\" content=\"");



#line 721 "..\..\Views\Account\Facebook.cshtml"
            WriteTo(@__razor_helper_writer, siteName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"fb:app_id\" content=\"");



#line 722 "..\..\Views\Account\Facebook.cshtml"
         WriteTo(@__razor_helper_writer, AppId);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>     \r\n");



WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:title\" content=\"");



#line 723 "..\..\Views\Account\Facebook.cshtml"
        WriteTo(@__razor_helper_writer, title);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:type\" content=\"");



#line 724 "..\..\Views\Account\Facebook.cshtml"
       WriteTo(@__razor_helper_writer, type);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:url\" content=\"");



#line 725 "..\..\Views\Account\Facebook.cshtml"
      WriteTo(@__razor_helper_writer, url);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:image\" content=\"");



#line 726 "..\..\Views\Account\Facebook.cshtml"
        WriteTo(@__razor_helper_writer, imageUrl);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>        \r\n");



#line 727 "..\..\Views\Account\Facebook.cshtml"
        if (!description.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:description\" content=\"");



#line 729 "..\..\Views\Account\Facebook.cshtml"
              WriteTo(@__razor_helper_writer, description);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 730 "..\..\Views\Account\Facebook.cshtml"
        }

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult OpenGraphLocationProperties(
    string latitude = "",
    string longitude = "",
    string streetAddress = "",
    string locality = "",
    string region = "",
    string postalCode = "",
    string countryName = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 750 "..\..\Views\Account\Facebook.cshtml"
             
        if (!latitude.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:latitude\" content=\"");



#line 753 "..\..\Views\Account\Facebook.cshtml"
           WriteTo(@__razor_helper_writer, latitude);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 754 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!longitude.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:longitude\" content=\"");



#line 757 "..\..\Views\Account\Facebook.cshtml"
            WriteTo(@__razor_helper_writer, longitude);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 758 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!streetAddress.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:street-address\" content=\"");



#line 761 "..\..\Views\Account\Facebook.cshtml"
                 WriteTo(@__razor_helper_writer, streetAddress);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 762 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!locality.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:locality\" content=\"");



#line 765 "..\..\Views\Account\Facebook.cshtml"
           WriteTo(@__razor_helper_writer, locality);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 766 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!region.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:region\" content=\"");



#line 769 "..\..\Views\Account\Facebook.cshtml"
         WriteTo(@__razor_helper_writer, region);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 770 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!postalCode.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:postal-code\" content=\"");



#line 773 "..\..\Views\Account\Facebook.cshtml"
              WriteTo(@__razor_helper_writer, postalCode);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 774 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!countryName.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:country-name\" content=\"");



#line 777 "..\..\Views\Account\Facebook.cshtml"
               WriteTo(@__razor_helper_writer, countryName);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 778 "..\..\Views\Account\Facebook.cshtml"
        }

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult OpenGraphContactProperties(
    string email = "",
    string phoneNumber = "",
    string faxNumber = "")
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 794 "..\..\Views\Account\Facebook.cshtml"
             
    
        if (!email.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:email\" content=\"");



#line 798 "..\..\Views\Account\Facebook.cshtml"
        WriteTo(@__razor_helper_writer, email);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 799 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!phoneNumber.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:phone_number\" content=\"");



#line 802 "..\..\Views\Account\Facebook.cshtml"
               WriteTo(@__razor_helper_writer, phoneNumber);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 803 "..\..\Views\Account\Facebook.cshtml"
        }
        if (!faxNumber.IsEmpty())
        {

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "    <meta property=\"og:fax_number\" content=\"");



#line 806 "..\..\Views\Account\Facebook.cshtml"
             WriteTo(@__razor_helper_writer, faxNumber);

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\"/>\r\n");



#line 807 "..\..\Views\Account\Facebook.cshtml"
        }
    

#line default
#line hidden

});

}


public System.Web.WebPages.HelperResult FbmlNamespaces()
    {
return new System.Web.WebPages.HelperResult(__razor_helper_writer => {



#line 817 "..\..\Views\Account\Facebook.cshtml"
     

#line default
#line hidden

WriteLiteralTo(@__razor_helper_writer, "\t");

WriteLiteralTo(@__razor_helper_writer, "xmlns:fb=\"http://www.facebook.com/2008/fbml\" xmlns:og=\"http://opengraphprotocol.o" +
"rg/schema/\"");

WriteLiteralTo(@__razor_helper_writer, " ");



#line 818 "..\..\Views\Account\Facebook.cshtml"
                                                                                                           
#line default
#line hidden

});

                                                                                                           }


        public Facebook()
        {
        }
        public override void Execute()
        {





WriteLiteral(":\r\n");




WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("  \r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n    \r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("     \r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n");



WriteLiteral("\r\n");


        }
    }
}
#pragma warning restore 1591
