//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Campaigns = new HashSet<Campaign>();
            this.ReceivingTransactions = new HashSet<Transaction>();
            this.SendingTransaction = new HashSet<Transaction>();
        }
    
        public int AccountID { get; set; }
        public System.Guid UserID { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int CurrentBalance { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
    
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<Transaction> ReceivingTransactions { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<Transaction> SendingTransaction { get; set; }
    }
}
