//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.Tags = new HashSet<Tag>();
            this.Files = new HashSet<File>();
        }
    
        public int AlbumId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> AlbumTypeID { get; set; }
        public Nullable<int> PrivacyLevelId { get; set; }
        public System.Guid UserID { get; set; }
        public Nullable<int> CampaignID { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual User User { get; set; }
        public virtual AlbumType AlbumType { get; set; }
        public virtual PrivacyLevel PrivacyLevel { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<File> Files { get; set; }
    }
}
