//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campaign_Users_RelationshipTypes
    {
        public Campaign_Users_RelationshipTypes()
        {
            this.CampaignUsers = new HashSet<Ref_CampaignUsers>();
        }
    
        public int RelationshipTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Ref_CampaignUsers> CampaignUsers { get; set; }
    }
}
