//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        public File()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int FileID { get; set; }
        public string Name { get; set; }
        public int FileTypeId { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
        public string ThumbnailUrl { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsAlbumCover { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<double> Rating { get; set; }
        public Nullable<int> LinkSourceId { get; set; }
        public System.Guid UserID { get; set; }
        public bool LikeLocked { get; set; }
        public bool SupportLocked { get; set; }
        public int DownloadRuleID { get; set; }
        public int PrivacyLevelID { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
        public Nullable<int> AlbumID { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual LinkSource LinkSource { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual User User { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual PrivacyLevel PrivacyLevel { get; set; }
        public virtual PrivacyLevel DownloadRule { get; set; }
        public virtual Album Album { get; set; }
        public virtual Product Product { get; set; }
    }
}
