//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public Goal()
        {
            this.Rewards = new HashSet<Reward>();
        }
    
        public int GoalID { get; set; }
        public string Name { get; set; }
        public int GoalTypeID { get; set; }
        public string Description { get; set; }
        public System.Guid UserID { get; set; }
        public string TargetNum { get; set; }
        public string QtyMax { get; set; }
        public System.DateTime TargetDate { get; set; }
        public System.DateTime ExpDate { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool Approved { get; set; }
        public bool Private { get; set; }
        public string Status { get; set; }
        public string YouTubeURL { get; set; }
        public string FBURL { get; set; }
        public string TwitterURL { get; set; }
        public string CurrentQTY { get; set; }
        public int CampaignID { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
    
        public virtual GoalType GoalType { get; set; }
        public virtual User Creator { get; set; }
        public virtual ICollection<Reward> Rewards { get; set; }
        public virtual Campaign Campaign { get; set; }
    }
}
