//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LinkSource
    {
        public LinkSource()
        {
            this.Links = new HashSet<File>();
        }
    
        public int LinkTypeID { get; set; }
        public string WebsiteName { get; set; }
        public string Description { get; set; }
        public string HomeURL { get; set; }
    
        public virtual ICollection<File> Links { get; set; }
    }
}
