//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public Purchase()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int PurchaseID { get; set; }
        public System.Guid UserID { get; set; }
        public int ProductID { get; set; }
        public int Date { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual User User { get; set; }
    }
}
