//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_UserConnections
    {
        public System.Guid UserID { get; set; }
        public System.Guid ConnectedUserID { get; set; }
        public int RelationshipTypeID { get; set; }
        public System.DateTime DateAdded { get; set; }
    
        public virtual User MainUser { get; set; }
        public virtual User ConectedUser { get; set; }
        public virtual User2User_RelationshipTypes User2User_RelationshipTypes { get; set; }
    }
}
