//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_CampaignUsers
    {
        public int CampaignID { get; set; }
        public System.Guid UserID { get; set; }
        public int RelationshipTypeID { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.Guid> AddedBy { get; set; }
    
        public virtual Campaign_Users_RelationshipTypes Campaign_Users_RelationshipTypes { get; set; }
        public virtual Campaign Campaign { get; set; }
        public virtual User User { get; set; }
        public virtual User AddedByUser { get; set; }
    }
}
