//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reward
    {
        public int RewardID { get; set; }
        public int RewardTypeID { get; set; }
        public System.Guid UserID { get; set; }
        public string Description { get; set; }
        public string Minimum { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public Nullable<int> MaxAvailable { get; set; }
        public int GoalID { get; set; }
        public Nullable<bool> IsDeactivated { get; set; }
        public Nullable<int> ProductID { get; set; }
    
        public virtual RewardType RewardType { get; set; }
        public virtual User Creator { get; set; }
        public virtual Goal Goal { get; set; }
        public virtual Product Product { get; set; }
    }
}
