//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SignYourselfEntities : DbContext
    {
        public SignYourselfEntities()
            : base("name=SignYourselfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<Activity> Activities { get; set; }
        public DbSet<ActivityType> ActivityTypes { get; set; }
        public DbSet<AlbumType> AlbumTypes { get; set; }
        public DbSet<Campaign_Users_RelationshipTypes> Campaign_Users_RelationshipTypes { get; set; }
        public DbSet<CampaignComment> CampaignComments { get; set; }
        public DbSet<CampaignReview> CampaignReviews { get; set; }
        public DbSet<Campaign> Campaigns { get; set; }
        public DbSet<CampaignType> CampaignTypes { get; set; }
        public DbSet<CampaignUpdate> CampaignUpdates { get; set; }
        public DbSet<File> Files { get; set; }
        public DbSet<FileType> FileTypes { get; set; }
        public DbSet<Genre> Genres { get; set; }
        public DbSet<Goal> Goals { get; set; }
        public DbSet<GoalType> GoalTypes { get; set; }
        public DbSet<LinkSource> LinkSources { get; set; }
        public DbSet<Message> Messages { get; set; }
        public DbSet<PrivacyLevel> PrivacyLevels { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<ProductType> ProductTypes { get; set; }
        public DbSet<Purchase> Purchases { get; set; }
        public DbSet<Ref_FeaturedCampaigns> Ref_FeaturedCampaigns { get; set; }
        public DbSet<Reward> Rewards { get; set; }
        public DbSet<RewardType> RewardTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Transaction> Transactions { get; set; }
        public DbSet<TransactionType> TransactionTypes { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<UserComment> UserComments { get; set; }
        public DbSet<webpages_FacebookCredentials> webpages_FacebookCredentials { get; set; }
        public DbSet<Ref_FeaturedUsers> Ref_FeaturedUsers { get; set; }
        public DbSet<Address> Addresses { get; set; }
        public DbSet<Application> Applications { get; set; }
        public DbSet<UserMembership> UserMemberships { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<Role> Roles { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Ref_UserConnections> Ref_UserConnections { get; set; }
        public DbSet<User2User_RelationshipTypes> User2User_RelationshipTypes { get; set; }
        public DbSet<Album> Albums { get; set; }
        public DbSet<Credit> Credits { get; set; }
        public DbSet<Ref_CampaignUsers> Ref_CampaignUsers { get; set; }
    }
}
