//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User2User_RelationshipTypes
    {
        public User2User_RelationshipTypes()
        {
            this.UserConnections = new HashSet<Ref_UserConnections>();
        }
    
        public int RelationshipTypeID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Ref_UserConnections> UserConnections { get; set; }
    }
}
