//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Signyourself2012.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Accounts = new HashSet<Account>();
            this.Activities = new HashSet<Activity>();
            this.Addresses = new HashSet<Address>();
            this.CampaignComments = new HashSet<CampaignComment>();
            this.CampaignReviews = new HashSet<CampaignReview>();
            this.Campaigns = new HashSet<Campaign>();
            this.CampaignUpdates = new HashSet<CampaignUpdate>();
            this.Files = new HashSet<File>();
            this.Goals = new HashSet<Goal>();
            this.MessagesRecieved = new HashSet<Message>();
            this.Products = new HashSet<Product>();
            this.Purchases = new HashSet<Purchase>();
            this.FeaturedUsers = new HashSet<Ref_FeaturedUsers>();
            this.Rewards = new HashSet<Reward>();
            this.CommentsLeft = new HashSet<UserComment>();
            this.Roles = new HashSet<Role>();
            this.UserComments = new HashSet<UserComment>();
            this.UserConnections = new HashSet<Ref_UserConnections>();
            this.UsersConnectedTo = new HashSet<Ref_UserConnections>();
            this.Albums = new HashSet<Album>();
            this.MessagesSent = new HashSet<Message>();
            this.CampaignUsers = new HashSet<Ref_CampaignUsers>();
            this.CampaignUsersAdded = new HashSet<Ref_CampaignUsers>();
        }
    
        public System.Guid ApplicationId { get; set; }
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public bool IsAnonymous { get; set; }
        public System.DateTime LastActivityDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual Application Application { get; set; }
        public virtual ICollection<CampaignComment> CampaignComments { get; set; }
        public virtual ICollection<CampaignReview> CampaignReviews { get; set; }
        public virtual ICollection<Campaign> Campaigns { get; set; }
        public virtual ICollection<CampaignUpdate> CampaignUpdates { get; set; }
        public virtual ICollection<File> Files { get; set; }
        public virtual ICollection<Goal> Goals { get; set; }
        public virtual UserMembership Membership { get; set; }
        public virtual ICollection<Message> MessagesRecieved { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual ICollection<Ref_FeaturedUsers> FeaturedUsers { get; set; }
        public virtual ICollection<Reward> Rewards { get; set; }
        public virtual ICollection<UserComment> CommentsLeft { get; set; }
        public virtual ICollection<Role> Roles { get; set; }
        public virtual ICollection<UserComment> UserComments { get; set; }
        public virtual ICollection<Ref_UserConnections> UserConnections { get; set; }
        public virtual ICollection<Ref_UserConnections> UsersConnectedTo { get; set; }
        public virtual ICollection<Album> Albums { get; set; }
        public virtual ICollection<Message> MessagesSent { get; set; }
        public virtual ICollection<Ref_CampaignUsers> CampaignUsers { get; set; }
        public virtual ICollection<Ref_CampaignUsers> CampaignUsersAdded { get; set; }
    }
}
